version: "3.8"
services:
  httpd:
    image: portfolio/httpd
    volumes:
      - ./vue:/var/www/vue
      - ./httpd/letsencrypt:/etc/letsencrypt
      - ./httpd/sites-enabled:/etc/apache2/sites-enabled
    ports:
      - "80:80"
      - "443:443"